---
roles:
  default:
    virtualbox:
      auto_nat_dns_proxy: false
      network:
        forwarded_port:
          guest: 80
          host: 8181
      customize: [[modifyvm, !ruby/sym id, '--memory', 4096]]
      customize: [[modifyvm, !ruby/sym id, '--cpus', 2]]
      customize: [[modifyvm, !ruby/sym id, '--natdnsproxy1', 'on']]
      customize: [[modifyvm, !ruby/sym id, --natdnshostresolver1', 'on']]
    synced_folders:
      # Disable Vagrant default
      - host_path: '.'
        guest_path: '/vagrant'
        disabled: true
      # Puppet Directories for Puppet 4.x
      - host_path: '../platform-configs/hieradata'
        guest_path: '/etc/puppet/environments/<%= ENV['PUPPET_ENV'] || 'vagrant' %>/hieradata'
        disabled: false
      - host_path: '../platform-puppet/modules'
        guest_path: '/etc/puppet/modules'
        disabled: false
      - host_path: '../platform-puppet/manifests'
        guest_path: '/etc/puppet/manifests'
        disabled: false
      - host_path: '../platform-configs/keys'
        guest_path: '/etc/puppet/secure/keys/'
        disabled: false
      # - host_path: '.rvm-vagrant-sync/<%=ENV['HOSTNAME'] %>' #This isn't going to work fwiw
      #   guest_path: '/usr/local/rvm'
      #   disabled: false
